#!/bin/bash
#
# bootstrap installs things.

function bootstrapTerminal() {	
	source ~/.dotfiles-server/installscript $1
}


echo 'Bootstrap terminal'
echo '------------------'
echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
read -p 'Answer: '  reply

if [[ $reply =~ ^[Yy]$ ]]
then
   bootstrapTerminal $1
fi
