#!/bin/bash

# Change dir to HOME
cd $HOME

# Symlink bash prefs
rm $HOME/.bash_profile
ln -rnfs $HOME/.dotfiles-server/shell/bash/bash_profile $HOME/.bash_profile

rm $HOME/.bashrc
ln -rnfs $HOME/.dotfiles-server/shell/bash/bashrc $HOME/.bashrc

rm $HOME/.bash_aliases
ln -rnfs $HOME/.dotfiles-server/shell/bash/bash_aliases $HOME/.bash_aliases

# Symlink common shell prefs
rm $HOME/.profile
ln -rnfs $HOME/.dotfiles-server/shell/profile $HOME/.profile

rm $HOME/.aliases
ln -rnfs $HOME/.dotfiles-server/shell/aliases $HOME/.aliases

rm $HOME/.exports
ln -rnfs $HOME/.dotfiles-server/shell/exports $HOME/.exports

rm $HOME/.functions
ln -rnfs $HOME/.dotfiles-server/shell/functions $HOME/.functions

# Symlink bin
rm -rf $HOME/bin
ln -rnfs $HOME/.dotfiles-server/bin $HOME/bin
chmod +x $HOME/bin/*

# Symlink config
rm -rf $HOME/.config
ln -rnfs $HOME/.dotfiles-server/config $HOME/.config

#Create .conditional-scripts
rm -rf "$HOME/.conditional-scripts"
touch "$HOME/.conditional-scripts"

for ARG in "$@"; do
    if [ "$ARG" = "plesk" ]; then
        rm -rf $HOME/.plesk
        ln -rnfs $HOME/.dotfiles-server/plesk $HOME/.plesk
        chmod +x $HOME/.plesk/bin/*
        echo "source ~/.plesk/init" >> "$HOME/.conditional-scripts"
    fi

    if [ "$ARG" = "neofetch" ]; then
        rm -rf $HOME/.neofetch
        git clone https://github.com/dylanaraps/neofetch.git $HOME/.neofetch
        chmod +x $HOME/.neofetch/neofetch
        echo "export PATH=\"\$HOME/.neofetch:\$PATH\"" >> "$HOME/.conditional-scripts"
        echo "neofetch" >> "$HOME/.conditional-scripts"
    fi
done

# Create .custom-scripts
if [ ! -f "$HOME/.custom-scripts" ]; then
    touch "$HOME/.custom-scripts"
fi

source $HOME/.bash_profile

php --version

composer self-update
