#!/bin/bash

# Change dir to HOME
cd ~

# Symlink bash prefs
rm ~/.bash_profile
ln -s ~/.dotfiles-server/shell/bash/bash_profile ~/.bash_profile

rm ~/.bashrc
ln -s ~/.dotfiles-server/shell/bash/bashrc ~/.bashrc

rm ~/.bash_aliases
ln -s ~/.dotfiles-server/shell/bash/bash_aliases ~/.bash_aliases

# Symlink common shell prefs
rm ~/.profile
ln -s ~/.dotfiles-server/shell/bash/profile ~/.profile

rm ~/.aliases
ln -s ~/.dotfiles-server/shell/aliases ~/.aliases

rm ~/.exports
ln -s ~/.dotfiles-server/shell/exports ~/.exports

rm ~/.functions
ln -s ~/.dotfiles-server/shell/functions ~/.functions

# Symlink bin
rm -rf ~/bin
ln -s ~/.dotfiles-server/bin ~/bin
chmod +x ~/bin/*

# Create .custom-scripts
touch ~/.custom-scripts

if [ "$1" = "plesk"]; then
    rm -rf ~/.plesk
    ln -rnfs ~/.dotfiles-server/plesk ~/.plesk
    echo "source ~/.plesk/init" >> "~/.custom-scripts"
fi

source ~/.bash_profile

php --version

composer self-update